name: CI/CD Pipeline on merge

'on':
  push:
    branches:
      - develop
      - main
  workflow_dispatch:


jobs:
  gitversion:
    name: GitVersion
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.Semver.outputs.FullSemVer }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v3.0.0
      - id: Semver
        uses: gittools/actions/gitversion/execute@v3.0.0

  build-views-service:
    name: Build Views Service
    needs: gitversion
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of views service
        run: dotnet restore 
        working-directory: src/Kaleido.Modules.Services.Grpc.Views
      - name: Build views service
        run: dotnet build
        working-directory: src/Kaleido.Modules.Services.Grpc.Views

  build-views-service-migrations:
    name: Build Views Service Migrations
    needs: gitversion
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of views service migrations
        run: dotnet restore
        working-directory: src/Kaleido.Modules.Services.Grpc.Views.Migrations
      - name: Build views service migrations
        run: dotnet build
        working-directory: src/Kaleido.Modules.Services.Grpc.Views.Migrations

  build-views-service-client:
    name: Build Views Service Client
    needs: gitversion
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of views service client
        run: dotnet restore
        working-directory: src/Kaleido.Modules.Services.Grpc.Views.Client
      - name: Build views service client
        run: dotnet build
        working-directory: src/Kaleido.Modules.Services.Grpc.Views.Client

  unit-tests:
    name: Run Unit Tests
    needs: [build-views-service, build-views-service-migrations, build-views-service-client]
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of unit tests
        run: dotnet restore
        working-directory: src/Kaleido.Modules.Services.Grpc.Views.Tests.Unit
      - name: Run unit tests
        run: dotnet test
        working-directory: src/Kaleido.Modules.Services.Grpc.Views.Tests.Unit

  create-service-release:
    name: Create Dotnet Release for service
    runs-on: ubuntu-latest
    needs: [build-views-service, build-views-service-migrations, build-views-service-client, gitversion]
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of service
        run: dotnet restore
        working-directory: src/Kaleido.Modules.Services.Grpc.Views
      - name: Build service Release
        run: dotnet build -c Release
        working-directory: src/Kaleido.Modules.Services.Grpc.Views
      - name: Upload Dotnet Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: views-service
          path: src/Kaleido.Modules.Services.Grpc.Views/bin/Release/net8.0

  create-migrations-release:
    name: Create Dotnet Release for migrations
    runs-on: ubuntu-latest
    needs: [build-views-service, build-views-service-migrations, build-views-service-client, gitversion]
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of migrations
        run: dotnet restore
        working-directory: src/Kaleido.Modules.Services.Grpc.Views.Migrations
      - name: Build migrations
        run: dotnet build -c Release
        working-directory: src/Kaleido.Modules.Services.Grpc.Views.Migrations
      - name: Upload Dotnet Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: views-service-migrations
          path: src/Kaleido.Modules.Services.Grpc.Views.Migrations/bin/Release/net8.0

  integration-tests:
    name: Run Integration Tests
    needs: [create-service-release, create-migrations-release, gitversion]
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of integration tests
        run: dotnet restore
        working-directory: src/Kaleido.Modules.Services.Grpc.Views.Tests.Integrations
      - name: Download Service Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: views-service
          path: service/out
      - name: Download Migrations Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: views-service-migrations
          path: migrations/out
      - name: Build Product Service Docker Image
        run: docker build . -f dockerfiles/Grpc.Views/Dockerfile.cicd -t kaleido-modules-services-grpc-views:${{ needs.gitversion.outputs.version }} --build-arg RELEASE_DIR=service/out
      - name: Build Migrations Docker Image
        run: docker build . -f dockerfiles/Grpc.Views.Migrations/Dockerfile.cicd -t kaleido-modules-services-grpc-views-migrations:${{ needs.gitversion.outputs.version }} --build-arg RELEASE_DIR=migrations/out
      - name: login to ghcr
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull Categories Image
        run: docker pull kaleido-modules-services-grpc-categories:latest
      - name: Pull Categories Migrations Image
        run: docker pull kaleido-modules-services-grpc-categories-migrations:latest
      - name: Run integration tests
        run: dotnet test
        working-directory: src/Kaleido.Modules.Services.Grpc.Views.Tests.Integrations
        env:
          VIEWS_IMAGE_NAME: kaleido-modules-services-grpc-views:${{ needs.gitversion.outputs.version }}
          MIGRATIONS_IMAGE_NAME: kaleido-modules-services-grpc-views-migrations:${{ needs.gitversion.outputs.version }}
          CI: true

  git-tag-release:
    name: Git Tag Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [integration-tests, unit-tests, gitversion]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          CUSTOM_TAG: ${{ needs.gitversion.outputs.version }}

  build-and-push-views-docker-image:
    name: Build and Push Views Service Docker Image
    needs: [git-tag-release, gitversion, create-service-release]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download Service Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: views-service
          path: service/out
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/Grpc.Views/Dockerfile.cicd
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            RELEASE_DIR=service/out
          tags: |
            ghcr.io/kaleido-organisation-manager/kaleido-modules-services-grpc-views:${{ needs.gitversion.outputs.version }}
            ghcr.io/kaleido-organisation-manager/kaleido-modules-services-grpc-views:latest

  build-and-push-migrations-docker-image:
    name: Build and Push Migrations Docker Image
    needs: [git-tag-release, gitversion, create-migrations-release]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download Migrations Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: views-service-migrations
          path: migrations/out
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/Grpc.Views.Migrations/Dockerfile.cicd
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            RELEASE_DIR=migrations/out
          tags: |
            ghcr.io/kaleido-organisation-manager/kaleido-modules-services-grpc-views-migrations:${{ needs.gitversion.outputs.version }}
            ghcr.io/kaleido-organisation-manager/kaleido-modules-services-grpc-views-migrations:latest

  create-client-release:
    name: Create Dotnet Release for client
    runs-on: ubuntu-latest
    needs: [git-tag-release, gitversion]
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of client
        run: dotnet restore
        working-directory: src/Kaleido.Modules.Services.Grpc.Views.Client
      - name: Pack dotnet package
        run: dotnet pack --configuration Release /p:Version=${{ needs.gitversion.outputs.version }} -o $GITHUB_WORKSPACE/client/out
        working-directory: src/Kaleido.Modules.Services.Grpc.Views.Client
      - name: Upload Dotnet Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: views-service-client
          path: client/out


  publish-client-package:
    name: Publish Client Package
    needs: [create-client-release, gitversion]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Download Client Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: views-service-client
          path: client/out
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Publish Client Package
        run: dotnet nuget push client/out/Kaleido.Modules.Services.Grpc.Views.Client.${{ needs.gitversion.outputs.version }}.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"

      
